dec_project2:
  outputs:
    dev:
      dataset: pj2_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: D:\Learning\BigData\dbt\data_warehouse_course\conf\service_acc_key.json
      location: US
      method: service-account
      priority: interactive
      project: dec-project-12
      threads: 4
      type: bigquery
  target: dev
